# .github/FUNDING.yml

# GitHub Sponsors (需先注册 GitHub Sponsors)
github: CikeZZZ

# 爱发电（中文开发者最常用！）
afdian: CikeZZZ

# 微信/支付宝收款（通过“赞赏码”等生成的链接）
custom: ["https://your-domain.com/donate.html"]

# 其他平台（可选）
patreon: CikeZZZ
ko_fi: CikeZZZ
liberapay: yourname
